# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75e2d0f7233c3bfc66e3cd8a14e7b2acb3ff4b1262ff8b864227573ecd4db009e0ae5778a7d8485589f1e6efd673b846ebff903cbbb2b51f78b6b8ce2184f83f

test:
  secret_key_base: 15bf4a07284e4a21ae83b98f67c9246d6773d97369f15ea98fc72361d628fbb3d99ac72a07911255e984a88e427133f376a525af2d3d8c4fd319b50ab423e1e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
